framework:
    templating:
        engines: ['twig', 'php']
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

        # config/packages/fos_user.yaml
        fos_user:
            db_driver: orm # other valid values are 'mongodb' and 'couchdb'
            firewall_name: main
            user_class: App\Entity\User
            from_email:
                address: "test@domain.com"
                sender_name: "test@domain.com"
